### PR TITLE
Add R and Svelte Language Icons

### PR DESCRIPTION
**Pull request by IndexingGitHub**

### CODE REVIEW

**Comment by PressJump** [comment]
Thank you for your pull request.
This project has been in a holding pattern for some time. The challenge in maintaining it primarily stems from the less-than-optimal state of the code and non-optimal use of typescript. Originally, the plan was to refactor and tidy it up but unfortunately, I haven't been able to allocate the necessary time to do so.

I'm currently planning (a sequel (may be under different naming) to this project), with a strong focus on enhancing various aspects such as source management, maintainability, structure, organization, and initial render speed. 

Although this is a good thing, this would mean reimaginedreadme would require significant alterations to the existing source code. Given the different direction on design and logical approaches I intend to implement like using a different framework that is more appropriate for this project, it seems to be more feasible starting afresh rather than retrofitting things into this project.

Following your pull request, and some changes to the source, I will add a clear warning in the project's embed and readme regarding its impending deprecation with a specific date about the shutdown of the service and its hosting on Vercel. On the soon to be listed date and following, the repository will be archived and the host on vercel will be shut down.

**Comment by IndexingGitHub** [comment]
> Thank you for your pull request. This project has been in a holding pattern for some time. The challenge in maintaining it primarily stems from the less-than-optimal state of the code and non-optimal use of typescript. Originally, the plan was to refactor and tidy it up but unfortunately, I haven't been able to allocate the necessary time to do so.
> 
> I'm currently planning (a sequel (may be under different naming) to this project), with a strong focus on enhancing various aspects such as source management, maintainability, structure, organization, and initial render speed.
> 
> Although this is a good thing, this would mean reimaginedreadme would require significant alterations to the existing source code. Given the different direction on design and logical approaches I intend to implement like using a different framework that is more appropriate for this project, it seems to be more feasible starting afresh rather than retrofitting things into this project.
> 
> Following your pull request, and some changes to the source, I will add a clear warning in the project's embed and readme regarding its impending deprecation with a specific date about the shutdown of the service and its hosting on Vercel. On the soon to be listed date and following, the repository will be archived and the host on vercel will be shut down.

Thanks for the response! I hope you create a new version soon. I was going to try and make some pull requests regarding the issues that are still open but me and my friend realized the errors from Typescript when making a fork. Have a good day :)

**Comment by IndexingGitHub** [comment]
Also, I'm not sure if you checked the code. It doesn't seem that Vercel properly deployed as the user having the problem still doesn't have the language icons for the R and Svelte language.

**Comment by PressJump** [comment]
> > Thank you for your pull request. This project has been in a holding pattern for some time. The challenge in maintaining it primarily stems from the less-than-optimal state of the code and non-optimal use of typescript. Originally, the plan was to refactor and tidy it up but unfortunately, I haven't been able to allocate the necessary time to do so.
> > I'm currently planning (a sequel (may be under different naming) to this project), with a strong focus on enhancing various aspects such as source management, maintainability, structure, organization, and initial render speed.
> > Although this is a good thing, this would mean reimaginedreadme would require significant alterations to the existing source code. Given the different direction on design and logical approaches I intend to implement like using a different framework that is more appropriate for this project, it seems to be more feasible starting afresh rather than retrofitting things into this project.
> > Following your pull request, and some changes to the source, I will add a clear warning in the project's embed and readme regarding its impending deprecation with a specific date about the shutdown of the service and its hosting on Vercel. On the soon to be listed date and following, the repository will be archived and the host on vercel will be shut down.
> 
> Thanks for the response! I hope you create a new version soon. I was going to try and make some pull requests regarding the issues that are still open but me and my friend realized the errors from Typescript when making a fork. Have a good day :)

Hey @IndexingGitHub thanks for your reply. Unfortunately I am busy nowdays due to other commitments and even though I was aware of the traffic on this repo was unable to act upon it. There is quite alot of typescript issues unfortunately as this project was prototyped together than properly built which is why I also want to work on a new version that is separate with better development choices.

I will get to your pull requests this week and will properly deprecate this project hopefully soon.

**Pull request merged**
