### PR TITLE
Added Kotlin & Swift icons

### PR DESCRIPTION
**Pull request by PierreJanineh**
Added missing Kotlin and Swift icons
Fixes issue #26 

Kotlin SVG source: https://www.vectorlogo.zone/logos/kotlinlang/index.html
Swift SVG source: https://www.vectorlogo.zone/logos/swift/index.html

### CODE REVIEW

**Review by PressJump — CHANGES_REQUESTED** [review]
Please use the up to date logo of Kotlin from their brand assets website found at https://kotlinlang.org/docs/kotlin-brand-assets.html#kotlin-logo .

**Comment by indexxing** [comment]
> Please use the up to date logo of Kotlin from their brand assets website found at https://kotlinlang.org/docs/kotlin-brand-assets.html#kotlin-logo .

I wasn't sure how to add to this pull request, however I made a pull request #34 that has the modernized Kotlin language icon.

**Comment by PressJump** [comment]
> > Please use the up to date logo of Kotlin from their brand assets website found at https://kotlinlang.org/docs/kotlin-brand-assets.html#kotlin-logo .
> 
> I wasn't sure how to add to this pull request, however I made a pull request #34 that has the modernized Kotlin language icon.

Hey @indexxing 
Thank you for your pull request. I will check it out today.

**Comment by PressJump** [comment]
Closed per Kotlin icon having restriction "Do not separate the mark from the text. Do not swap elements.".

**Pull request closed without merging**
